/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ID = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;

export interface ConfigSchema {
  commonSetting: NoName;
}
export interface NoName {
  appId: ID;
  name: NoName1;
  getProcessManagementResponse?: NoName2;
  getFormFieldsResponse?: NoName3;
}
